// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_bufs/travel_mate.proto

package travel_matepb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//CandidateSource describes sources of this candidate, could be Google, Yelp or some other source.
type CandidateSource struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Rating               float32  `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	ReviewCount          int32    `protobuf:"varint,4,opt,name=reviewCount,proto3" json:"reviewCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CandidateSource) Reset()         { *m = CandidateSource{} }
func (m *CandidateSource) String() string { return proto.CompactTextString(m) }
func (*CandidateSource) ProtoMessage()    {}
func (*CandidateSource) Descriptor() ([]byte, []int) {
	return fileDescriptor_19974c3c9defe761, []int{0}
}

func (m *CandidateSource) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateSource.Unmarshal(m, b)
}
func (m *CandidateSource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateSource.Marshal(b, m, deterministic)
}
func (m *CandidateSource) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateSource.Merge(m, src)
}
func (m *CandidateSource) XXX_Size() int {
	return xxx_messageInfo_CandidateSource.Size(m)
}
func (m *CandidateSource) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateSource.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateSource proto.InternalMessageInfo

func (m *CandidateSource) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CandidateSource) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CandidateSource) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *CandidateSource) GetReviewCount() int32 {
	if m != nil {
		return m.ReviewCount
	}
	return 0
}

//ReviewAuthor described data model for author who adds a review
type ReviewAuthor struct {
	ProfileUrl           string   `protobuf:"bytes,1,opt,name=profile_url,json=profileUrl,proto3" json:"profile_url,omitempty"`
	ImageUrl             string   `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReviewAuthor) Reset()         { *m = ReviewAuthor{} }
func (m *ReviewAuthor) String() string { return proto.CompactTextString(m) }
func (*ReviewAuthor) ProtoMessage()    {}
func (*ReviewAuthor) Descriptor() ([]byte, []int) {
	return fileDescriptor_19974c3c9defe761, []int{1}
}

func (m *ReviewAuthor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReviewAuthor.Unmarshal(m, b)
}
func (m *ReviewAuthor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReviewAuthor.Marshal(b, m, deterministic)
}
func (m *ReviewAuthor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReviewAuthor.Merge(m, src)
}
func (m *ReviewAuthor) XXX_Size() int {
	return xxx_messageInfo_ReviewAuthor.Size(m)
}
func (m *ReviewAuthor) XXX_DiscardUnknown() {
	xxx_messageInfo_ReviewAuthor.DiscardUnknown(m)
}

var xxx_messageInfo_ReviewAuthor proto.InternalMessageInfo

func (m *ReviewAuthor) GetProfileUrl() string {
	if m != nil {
		return m.ProfileUrl
	}
	return ""
}

func (m *ReviewAuthor) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *ReviewAuthor) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

//Review desribes data model for user review
type Review struct {
	Author                  *ReviewAuthor `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Rating                  int32         `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	RelativeTimeDescription string        `protobuf:"bytes,3,opt,name=relative_time_description,json=relativeTimeDescription,proto3" json:"relative_time_description,omitempty"`
	Text                    string        `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Time                    string        `protobuf:"bytes,5,opt,name=time,proto3" json:"time,omitempty"`
	Source                  string        `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}      `json:"-"`
	XXX_unrecognized        []byte        `json:"-"`
	XXX_sizecache           int32         `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_19974c3c9defe761, []int{2}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetAuthor() *ReviewAuthor {
	if m != nil {
		return m.Author
	}
	return nil
}

func (m *Review) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Review) GetRelativeTimeDescription() string {
	if m != nil {
		return m.RelativeTimeDescription
	}
	return ""
}

func (m *Review) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Review) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Review) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type Coordinates struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coordinates) Reset()         { *m = Coordinates{} }
func (m *Coordinates) String() string { return proto.CompactTextString(m) }
func (*Coordinates) ProtoMessage()    {}
func (*Coordinates) Descriptor() ([]byte, []int) {
	return fileDescriptor_19974c3c9defe761, []int{3}
}

func (m *Coordinates) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coordinates.Unmarshal(m, b)
}
func (m *Coordinates) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coordinates.Marshal(b, m, deterministic)
}
func (m *Coordinates) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coordinates.Merge(m, src)
}
func (m *Coordinates) XXX_Size() int {
	return xxx_messageInfo_Coordinates.Size(m)
}
func (m *Coordinates) XXX_DiscardUnknown() {
	xxx_messageInfo_Coordinates.DiscardUnknown(m)
}

var xxx_messageInfo_Coordinates proto.InternalMessageInfo

func (m *Coordinates) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coordinates) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

//Candidate represents TravelMate Business data model
type Candidate struct {
	Sources              []*CandidateSource `protobuf:"bytes,1,rep,name=sources,proto3" json:"sources,omitempty"`
	Name                 string             `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsClosed             bool               `protobuf:"varint,3,opt,name=is_closed,json=isClosed,proto3" json:"is_closed,omitempty"`
	Website              string             `protobuf:"bytes,4,opt,name=website,proto3" json:"website,omitempty"`
	Coordinates          *Coordinates       `protobuf:"bytes,5,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	FormattedAddress     string             `protobuf:"bytes,6,opt,name=formatted_address,json=formattedAddress,proto3" json:"formatted_address,omitempty"`
	Price                string             `protobuf:"bytes,7,opt,name=price,proto3" json:"price,omitempty"`
	Phone                string             `protobuf:"bytes,8,opt,name=phone,proto3" json:"phone,omitempty"`
	DisplayPhone         string             `protobuf:"bytes,9,opt,name=display_phone,json=displayPhone,proto3" json:"display_phone,omitempty"`
	Distance             float64            `protobuf:"fixed64,10,opt,name=distance,proto3" json:"distance,omitempty"`
	Photos               []string           `protobuf:"bytes,11,rep,name=photos,proto3" json:"photos,omitempty"`
	Reviews              []*Review          `protobuf:"bytes,12,rep,name=reviews,proto3" json:"reviews,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Candidate) Reset()         { *m = Candidate{} }
func (m *Candidate) String() string { return proto.CompactTextString(m) }
func (*Candidate) ProtoMessage()    {}
func (*Candidate) Descriptor() ([]byte, []int) {
	return fileDescriptor_19974c3c9defe761, []int{4}
}

func (m *Candidate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Candidate.Unmarshal(m, b)
}
func (m *Candidate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Candidate.Marshal(b, m, deterministic)
}
func (m *Candidate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Candidate.Merge(m, src)
}
func (m *Candidate) XXX_Size() int {
	return xxx_messageInfo_Candidate.Size(m)
}
func (m *Candidate) XXX_DiscardUnknown() {
	xxx_messageInfo_Candidate.DiscardUnknown(m)
}

var xxx_messageInfo_Candidate proto.InternalMessageInfo

func (m *Candidate) GetSources() []*CandidateSource {
	if m != nil {
		return m.Sources
	}
	return nil
}

func (m *Candidate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Candidate) GetIsClosed() bool {
	if m != nil {
		return m.IsClosed
	}
	return false
}

func (m *Candidate) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Candidate) GetCoordinates() *Coordinates {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

func (m *Candidate) GetFormattedAddress() string {
	if m != nil {
		return m.FormattedAddress
	}
	return ""
}

func (m *Candidate) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Candidate) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *Candidate) GetDisplayPhone() string {
	if m != nil {
		return m.DisplayPhone
	}
	return ""
}

func (m *Candidate) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *Candidate) GetPhotos() []string {
	if m != nil {
		return m.Photos
	}
	return nil
}

func (m *Candidate) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

//CandidateList represents TravelMate Business data model
type CandidateList struct {
	Candidates           []*Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Total                int32        `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CandidateList) Reset()         { *m = CandidateList{} }
func (m *CandidateList) String() string { return proto.CompactTextString(m) }
func (*CandidateList) ProtoMessage()    {}
func (*CandidateList) Descriptor() ([]byte, []int) {
	return fileDescriptor_19974c3c9defe761, []int{5}
}

func (m *CandidateList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CandidateList.Unmarshal(m, b)
}
func (m *CandidateList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CandidateList.Marshal(b, m, deterministic)
}
func (m *CandidateList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CandidateList.Merge(m, src)
}
func (m *CandidateList) XXX_Size() int {
	return xxx_messageInfo_CandidateList.Size(m)
}
func (m *CandidateList) XXX_DiscardUnknown() {
	xxx_messageInfo_CandidateList.DiscardUnknown(m)
}

var xxx_messageInfo_CandidateList proto.InternalMessageInfo

func (m *CandidateList) GetCandidates() []*Candidate {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func (m *CandidateList) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

type PlaceSearchRequest struct {
	Text                 string   `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Latitude             float64  `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Radius               int32    `protobuf:"varint,4,opt,name=radius,proto3" json:"radius,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceSearchRequest) Reset()         { *m = PlaceSearchRequest{} }
func (m *PlaceSearchRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceSearchRequest) ProtoMessage()    {}
func (*PlaceSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_19974c3c9defe761, []int{6}
}

func (m *PlaceSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceSearchRequest.Unmarshal(m, b)
}
func (m *PlaceSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceSearchRequest.Marshal(b, m, deterministic)
}
func (m *PlaceSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceSearchRequest.Merge(m, src)
}
func (m *PlaceSearchRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceSearchRequest.Size(m)
}
func (m *PlaceSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceSearchRequest proto.InternalMessageInfo

func (m *PlaceSearchRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *PlaceSearchRequest) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *PlaceSearchRequest) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *PlaceSearchRequest) GetRadius() int32 {
	if m != nil {
		return m.Radius
	}
	return 0
}

type PlaceSearchResponse struct {
	Candidates           []*Candidate `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PlaceSearchResponse) Reset()         { *m = PlaceSearchResponse{} }
func (m *PlaceSearchResponse) String() string { return proto.CompactTextString(m) }
func (*PlaceSearchResponse) ProtoMessage()    {}
func (*PlaceSearchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_19974c3c9defe761, []int{7}
}

func (m *PlaceSearchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceSearchResponse.Unmarshal(m, b)
}
func (m *PlaceSearchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceSearchResponse.Marshal(b, m, deterministic)
}
func (m *PlaceSearchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceSearchResponse.Merge(m, src)
}
func (m *PlaceSearchResponse) XXX_Size() int {
	return xxx_messageInfo_PlaceSearchResponse.Size(m)
}
func (m *PlaceSearchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceSearchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceSearchResponse proto.InternalMessageInfo

func (m *PlaceSearchResponse) GetCandidates() []*Candidate {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func init() {
	proto.RegisterType((*CandidateSource)(nil), "travel_mate.CandidateSource")
	proto.RegisterType((*ReviewAuthor)(nil), "travel_mate.ReviewAuthor")
	proto.RegisterType((*Review)(nil), "travel_mate.Review")
	proto.RegisterType((*Coordinates)(nil), "travel_mate.Coordinates")
	proto.RegisterType((*Candidate)(nil), "travel_mate.Candidate")
	proto.RegisterType((*CandidateList)(nil), "travel_mate.CandidateList")
	proto.RegisterType((*PlaceSearchRequest)(nil), "travel_mate.PlaceSearchRequest")
	proto.RegisterType((*PlaceSearchResponse)(nil), "travel_mate.PlaceSearchResponse")
}

func init() { proto.RegisterFile("proto_bufs/travel_mate.proto", fileDescriptor_19974c3c9defe761) }

var fileDescriptor_19974c3c9defe761 = []byte{
	// 640 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x4a,
	0x14, 0x7d, 0x76, 0xda, 0x7c, 0x5c, 0xb7, 0xaf, 0xef, 0x4d, 0x51, 0x71, 0x4b, 0xa5, 0x46, 0x66,
	0x13, 0x09, 0x51, 0x44, 0x90, 0xba, 0xe8, 0xae, 0x04, 0x89, 0x0d, 0x48, 0xd5, 0x14, 0x36, 0x48,
	0xc8, 0x4c, 0x3c, 0xb7, 0xcd, 0x48, 0xb6, 0xc7, 0xcc, 0x8c, 0x53, 0xe0, 0x2f, 0xf1, 0x63, 0xf8,
	0x4b, 0xc8, 0x33, 0xe3, 0xc4, 0x29, 0x85, 0x05, 0x3b, 0x9f, 0x73, 0x8f, 0x7c, 0x3f, 0xce, 0xb1,
	0xe1, 0xb8, 0x52, 0xd2, 0xc8, 0x74, 0x5e, 0x5f, 0xeb, 0x67, 0x46, 0xb1, 0x25, 0xe6, 0x69, 0xc1,
	0x0c, 0x9e, 0x5a, 0x9a, 0x44, 0x1d, 0x2a, 0x91, 0xb0, 0x37, 0x63, 0x25, 0x17, 0x9c, 0x19, 0xbc,
	0x92, 0xb5, 0xca, 0x90, 0x10, 0xd8, 0x2a, 0x59, 0x81, 0x71, 0x30, 0x0e, 0x26, 0x23, 0x6a, 0x9f,
	0xc9, 0xbf, 0x10, 0x0a, 0x1e, 0x87, 0x96, 0x09, 0x05, 0x27, 0x07, 0xd0, 0x57, 0xcc, 0x88, 0xf2,
	0x26, 0xee, 0x8d, 0x83, 0x49, 0x48, 0x3d, 0x22, 0x63, 0x88, 0x14, 0x2e, 0x05, 0xde, 0xce, 0x64,
	0x5d, 0x9a, 0x78, 0x6b, 0x1c, 0x4c, 0xb6, 0x69, 0x97, 0x4a, 0x3e, 0xc1, 0x0e, 0xb5, 0xf0, 0xa2,
	0x36, 0x0b, 0xa9, 0xc8, 0x09, 0x44, 0x95, 0x92, 0xd7, 0x22, 0xc7, 0xb4, 0x56, 0xb9, 0x6f, 0x0a,
	0x9e, 0x7a, 0xaf, 0x72, 0xf2, 0x08, 0x46, 0xa2, 0x60, 0x37, 0xae, 0xec, 0x26, 0x18, 0x5a, 0xa2,
	0x29, 0xb6, 0xb3, 0xf6, 0xd6, 0xb3, 0x26, 0x3f, 0x02, 0xe8, 0xbb, 0x16, 0xe4, 0x39, 0xf4, 0x99,
	0x6d, 0x63, 0xdf, 0x1b, 0x4d, 0x0f, 0x4f, 0xbb, 0xe7, 0xe8, 0xce, 0x41, 0xbd, 0xb0, 0xb3, 0x59,
	0x68, 0x87, 0x6f, 0x37, 0x3b, 0x87, 0x43, 0x85, 0x39, 0x33, 0x62, 0x89, 0xa9, 0x11, 0x05, 0xa6,
	0x1c, 0x75, 0xa6, 0x44, 0x65, 0x84, 0x2c, 0x7d, 0xfb, 0x87, 0xad, 0xe0, 0x9d, 0x28, 0xf0, 0xd5,
	0xba, 0xdc, 0x4c, 0x69, 0xf0, 0x8b, 0x3b, 0xc7, 0x88, 0xda, 0x67, 0xcb, 0x89, 0x02, 0xe3, 0x6d,
	0xcf, 0x89, 0x02, 0x9b, 0xde, 0xda, 0x7a, 0x10, 0xf7, 0x2d, 0xeb, 0x51, 0xf2, 0x1a, 0xa2, 0x99,
	0x94, 0x8a, 0x8b, 0x92, 0x19, 0xd4, 0xe4, 0x08, 0x86, 0x4d, 0x1f, 0x53, 0x73, 0x67, 0x52, 0x40,
	0x57, 0x98, 0x1c, 0xc3, 0x28, 0x97, 0xe5, 0x8d, 0x2b, 0x86, 0xb6, 0xb8, 0x26, 0x92, 0xef, 0x3d,
	0x18, 0xad, 0xec, 0x26, 0x67, 0x30, 0x70, 0x0d, 0x74, 0x1c, 0x8c, 0x7b, 0x93, 0x68, 0x7a, 0xbc,
	0x71, 0x9e, 0x3b, 0xb9, 0xa0, 0xad, 0x78, 0x75, 0xf4, 0xb0, 0x13, 0x90, 0xc6, 0x25, 0x9d, 0x66,
	0xb9, 0xd4, 0xc8, 0xed, 0x39, 0x86, 0x74, 0x28, 0xf4, 0xcc, 0x62, 0x12, 0xc3, 0xe0, 0x16, 0xe7,
	0x5a, 0x18, 0xf4, 0x27, 0x68, 0x21, 0x39, 0x87, 0x28, 0x5b, 0x6f, 0x66, 0x8f, 0x11, 0x4d, 0xe3,
	0xcd, 0x31, 0xd6, 0x75, 0xda, 0x15, 0x93, 0x27, 0xf0, 0xff, 0xb5, 0x54, 0x05, 0x33, 0x06, 0x79,
	0xca, 0x38, 0x57, 0xa8, 0xb5, 0x3f, 0xdc, 0x7f, 0xab, 0xc2, 0x85, 0xe3, 0xc9, 0x03, 0xd8, 0xae,
	0x94, 0xc8, 0x30, 0x1e, 0x58, 0x81, 0x03, 0x96, 0x5d, 0xc8, 0x12, 0xe3, 0xa1, 0x67, 0x1b, 0x40,
	0x1e, 0xc3, 0x2e, 0x17, 0xba, 0xca, 0xd9, 0xd7, 0xd4, 0x55, 0x47, 0xb6, 0xba, 0xe3, 0xc9, 0x4b,
	0x2b, 0x3a, 0x82, 0x21, 0x17, 0xda, 0xb0, 0x32, 0xc3, 0x18, 0x9c, 0x09, 0x2d, 0x6e, 0x7c, 0xac,
	0x16, 0xd2, 0x48, 0x1d, 0x47, 0xe3, 0x5e, 0xe3, 0xa3, 0x43, 0xe4, 0x29, 0x0c, 0xdc, 0xa7, 0xa0,
	0xe3, 0x1d, 0x7b, 0xf0, 0xfd, 0x7b, 0xf2, 0x48, 0x5b, 0x4d, 0xf2, 0x11, 0x76, 0x57, 0x1e, 0xbc,
	0x11, 0xda, 0x90, 0x33, 0x80, 0xac, 0x25, 0x5a, 0xcf, 0x0e, 0xee, 0xf7, 0x8c, 0x76, 0x94, 0xcd,
	0x9a, 0x46, 0x1a, 0x96, 0xfb, 0x48, 0x3b, 0x90, 0x7c, 0x03, 0x72, 0x99, 0xb3, 0x0c, 0xaf, 0x90,
	0xa9, 0x6c, 0x41, 0xf1, 0x73, 0x8d, 0xda, 0xac, 0xb2, 0x1a, 0x74, 0xb2, 0xda, 0x0d, 0x5c, 0xf8,
	0xa7, 0xc0, 0xf5, 0xee, 0x04, 0xce, 0x7d, 0x4d, 0x5c, 0xd4, 0xda, 0xff, 0x0a, 0x3c, 0x4a, 0xde,
	0xc2, 0xfe, 0x46, 0x6f, 0x5d, 0xc9, 0x52, 0xe3, 0xdf, 0x2e, 0x38, 0x5d, 0x6c, 0xac, 0x72, 0x85,
	0x6a, 0xd9, 0xb8, 0x4b, 0x21, 0xea, 0xb0, 0xe4, 0x64, 0xe3, 0x45, 0xbf, 0xae, 0x7e, 0x34, 0xfe,
	0xbd, 0xc0, 0xcd, 0x97, 0xfc, 0xf3, 0x72, 0xef, 0xc3, 0x6e, 0x47, 0x54, 0xcd, 0xe7, 0x7d, 0xfb,
	0x53, 0x7d, 0xf1, 0x33, 0x00, 0x00, 0xff, 0xff, 0x98, 0x75, 0xfb, 0xc0, 0x74, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlaceSearchServiceClient is the client API for PlaceSearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaceSearchServiceClient interface {
	PlaceSearch(ctx context.Context, in *PlaceSearchRequest, opts ...grpc.CallOption) (*PlaceSearchResponse, error)
}

type placeSearchServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlaceSearchServiceClient(cc *grpc.ClientConn) PlaceSearchServiceClient {
	return &placeSearchServiceClient{cc}
}

func (c *placeSearchServiceClient) PlaceSearch(ctx context.Context, in *PlaceSearchRequest, opts ...grpc.CallOption) (*PlaceSearchResponse, error) {
	out := new(PlaceSearchResponse)
	err := c.cc.Invoke(ctx, "/travel_mate.PlaceSearchService/PlaceSearch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaceSearchServiceServer is the server API for PlaceSearchService service.
type PlaceSearchServiceServer interface {
	PlaceSearch(context.Context, *PlaceSearchRequest) (*PlaceSearchResponse, error)
}

// UnimplementedPlaceSearchServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPlaceSearchServiceServer struct {
}

func (*UnimplementedPlaceSearchServiceServer) PlaceSearch(ctx context.Context, req *PlaceSearchRequest) (*PlaceSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceSearch not implemented")
}

func RegisterPlaceSearchServiceServer(s *grpc.Server, srv PlaceSearchServiceServer) {
	s.RegisterService(&_PlaceSearchService_serviceDesc, srv)
}

func _PlaceSearchService_PlaceSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceSearchServiceServer).PlaceSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/travel_mate.PlaceSearchService/PlaceSearch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceSearchServiceServer).PlaceSearch(ctx, req.(*PlaceSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlaceSearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "travel_mate.PlaceSearchService",
	HandlerType: (*PlaceSearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PlaceSearch",
			Handler:    _PlaceSearchService_PlaceSearch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto_bufs/travel_mate.proto",
}
